NodePath {
  parent:
   Node {
     type: 'Program',
     start: 0,
     end: 110,
     loc: SourceLocation { start: [Object], end: [Object] },
     sourceType: 'module',
     body: [ [Object], [Object] ],
     directives: [] },
//hub属性很重要，Hub对象
  hub:
   Hub {
     file:
      File {
        _c: Map {},
        dynamicData: {},
        pipeline: Pipeline {},
        log: [Object],
        opts: [Object],
        parserOpts: [Object],
        pluginVisitors: [Object],
        pluginPasses: [Object],
        metadata: [Object],
        dynamicImportTypes: {},
        dynamicImportIds: {},
        dynamicImports: [],
        declarations: {},
        usedHelpers: {},
        path: [Object],
        ast: [Object],
        code: '\nclass Component3a extends React.Component {\n  render() {\n    return React.createElement(\'div\', null);\n  }\n};\n',
        shebang: '',
        hub: [Circular],
        scope: [Object] },
     options: undefined },
  //contexts属性
  contexts:
   [ TraversalContext {
       queue: [Object],
       parentPath: [Object],
       scope: [Object],
       state: undefined,
       opts: [Object],
       priorityQueue: [] } ],
  data: {},
  shouldSkip: false,
  shouldStop: false,
  removed: false,
  state: undefined,
  //这是我提供的对AST遍历的path
  opts:
   { ClassDeclaration: { enter: [Object] },
     FunctionDeclaration: { enter: [Object] },
     FunctionExpression: { enter: [Object] },
     ArrowFunctionExpression: { enter: [Object] },
     _exploded: {},
     _verified: {},
     BlockStatement: { exit: [Object] },
     Program: { exit: [Object] },
     ThisExpression: { enter: [Object] },
     Identifier: { enter: [Object] },
     JSXIdentifier: { enter: [Object] } },
  skipKeys: {},
  parentPath:
   NodePath {
     parent:
      Node {
        type: 'File',
        start: 0,
        end: 110,
        loc: [Object],
        program: [Object],
        comments: [],
        tokens: [Object] },
     hub: Hub { file: [Object], options: undefined },
     contexts: [ [Object] ],
     data: {},
     shouldSkip: false,
     shouldStop: false,
     removed: false,
     state: undefined,
     opts:
      { ClassDeclaration: [Object],
        FunctionDeclaration: [Object],
        FunctionExpression: [Object],
        ArrowFunctionExpression: [Object],
        _exploded: {},
        _verified: {},
        BlockStatement: [Object],
        Program: [Object],
        ThisExpression: [Object],
        Identifier: [Object],
        JSXIdentifier: [Object] },
     skipKeys: {},
     parentPath: null,
     context:
      TraversalContext {
        queue: [Object],
        parentPath: undefined,
        scope: [Object],
        state: undefined,
        opts: [Object],
        priorityQueue: [] },
     container:
      Node {
        type: 'File',
        start: 0,
        end: 110,
        loc: [Object],
        program: [Object],
        comments: [],
        tokens: [Object] },
     listKey: undefined,
     inList: false,
     parentKey: 'program',
     key: 'program',
     node:
      Node {
        type: 'Program',
        start: 0,
        end: 110,
        loc: [Object],
        sourceType: 'module',
        body: [Object],
        directives: [] },
     scope:
     //scope函数作用域
      Scope {
        uid: 0,
        parent: null,
        hub: [Object],
        parentBlock: [Object],
        block: [Object],
        path: [Circular],
        //是对path的循环引用
        labels: [Object],
        references: [Object],
        bindings: [Object],
        globals: [Object],
        uids: {},
        data: {},
        crawling: false
      },
     type: 'Program',
     typeAnnotation: null },
  context:
   TraversalContext {
     queue: [ [Circular] ],
     parentPath:
      NodePath {
        parent: [Object],
        hub: [Object],
        contexts: [Object],
        data: {},
        shouldSkip: false,
        shouldStop: false,
        removed: false,
        state: undefined,
        opts: [Object],
        skipKeys: {},
        parentPath: null,
        context: [Object],
        container: [Object],
        listKey: undefined,
        inList: false,
        parentKey: 'program',
        key: 'program',
        node: [Object],
        scope: [Object],
        type: 'Program',
        typeAnnotation: null },
     scope:
      Scope {
        uid: 0,
        parent: null,
        hub: [Object],
        parentBlock: [Object],
        block: [Object],
        path: [Object],
        labels: [Object],
        references: [Object],
        bindings: [Object],
        globals: [Object],
        uids: {},
        data: {},
        crawling: false },
     state: undefined,
     opts:
      { ClassDeclaration: [Object],
        FunctionDeclaration: [Object],
        FunctionExpression: [Object],
        ArrowFunctionExpression: [Object],
        _exploded: {},
        _verified: {},
        BlockStatement: [Object],
        Program: [Object],
        ThisExpression: [Object],
        Identifier: [Object],
        JSXIdentifier: [Object] },
     priorityQueue: [] },
  container:
   [ Node {
       type: 'ClassDeclaration',
       start: 1,
       end: 108,
       loc: [Object],
       id: [Object],
       superClass: [Object],
       body: [Object] },
     Node { type: 'EmptyStatement', start: 108, end: 109, loc: [Object] } ],
  listKey: 'body',
  inList: true,
  parentKey: 'body',
  key: 0,
  node:
   Node {
     type: 'ClassDeclaration',
     start: 1,
     end: 108,
     loc: SourceLocation { start: [Object], end: [Object] },
     id:
      Node {
        type: 'Identifier',
        start: 7,
        end: 18,
        loc: [Object],
        name: 'Component3a' },
     superClass:
      Node {
        type: 'MemberExpression',
        start: 27,
        end: 42,
        loc: [Object],
        object: [Object],
        property: [Object],
        computed: false },
     body:
      Node {
        type: 'ClassBody',
        start: 43,
        end: 108,
        loc: [Object],
        body: [Object] } },
  scope:
   Scope {
     uid: 1,
     parent:
      Scope {
        uid: 0,
        parent: null,
        hub: [Object],
        parentBlock: [Object],
        block: [Object],
        path: [Object],
        labels: [Object],
        references: [Object],
        bindings: [Object],
        globals: [Object],
        uids: {},
        data: {},
        crawling: false },
     hub: Hub { file: [Object], options: undefined },
     parentBlock:
      Node {
        type: 'Program',
        start: 0,
        end: 110,
        loc: [Object],
        sourceType: 'module',
        body: [Object],
        directives: [] },
     block:
      Node {
        type: 'ClassDeclaration',
        start: 1,
        end: 108,
        loc: [Object],
        id: [Object],
        superClass: [Object],
        body: [Object] },
     path: [Circular],
     labels: Map { _c: Map {} },
     references: {},
     bindings: { Component3a: [Object] },
     globals: {},
     uids: {},
     data: {} },
  type: 'ClassDeclaration',
  typeAnnotation: null }
