PluginPass {
  _c: Map {},
  dynamicData: {},
  plugin:
   Plugin {
     _c: Map {},
     dynamicData: {},
     initialized: true,
     raw: {},
     key: 'base$0',
     manipulateOptions: undefined,
     post: undefined,
     pre: undefined,
     //这里plugin对应的visitor
     visitor:
      { ClassDeclaration: [Object],
        FunctionDeclaration: [Object],
        FunctionExpression: [Object],
        ArrowFunctionExpression: [Object],
        _exploded: true,
        _verified: true } },
  key: 'base$0',
  file:
   File {
     _c: Map {},
     dynamicData: {},
     pipeline: Pipeline {},
     log: Logger { filename: 'unknown', file: [Circular] },
     //我们的配置信息通过state.file.opts来访问
     opts:
      { filename: 'unknown',
        filenameRelative: 'unknown',
        inputSourceMap: undefined,
        env: {},
        mode: undefined,
        retainLines: false,
        highlightCode: true,
        suppressDeprecationMessages: false,
        presets: [],
        plugins: [Object],
        ignore: [],
        only: undefined,
        code: true,
        metadata: true,
        ast: true,
        extends: undefined,
        comments: true,
        shouldPrintComment: undefined,
        wrapPluginVisitorMethod: undefined,
        compact: 'auto',
        minified: false,
        sourceMap: undefined,
        sourceMaps: undefined,
        sourceMapTarget: 'unknown',
        sourceFileName: 'unknown',
        sourceRoot: undefined,
        babelrc: true,
        sourceType: 'module',
        auxiliaryCommentBefore: undefined,
        auxiliaryCommentAfter: undefined,
        resolveModuleSource: undefined,
        getModuleId: undefined,
        moduleRoot: undefined,
        moduleIds: false,
        moduleId: undefined,
        passPerPreset: false,
        parserOpts: false,
        generatorOpts: false,
        basename: 'unknown' },
     parserOpts: { sourceType: 'module', sourceFileName: 'unknown', plugins: [] },
     pluginVisitors: [ [Object] ],
     pluginPasses: [ [Object] ],
     metadata: { usedHelpers: [], marked: [], modules: [Object] },
     dynamicImportTypes: {},
     dynamicImportIds: {},
     dynamicImports: [],
     declarations: {},
     usedHelpers: {},
     path:
      NodePath {
        parent: [Object],
        hub: [Object],
        contexts: [Object],
        data: {},
        shouldSkip: false,
        shouldStop: false,
        removed: false,
        state: undefined,
        opts: [Object],
        skipKeys: {},
        parentPath: null,
        context: [Object],
        container: [Object],
        listKey: undefined,
        inList: false,
        parentKey: 'program',
        key: 'program',
        node: [Object],
        scope: [Object],
        type: 'Program',
        typeAnnotation: null },
     ast:
      Node {
        type: 'File',
        start: 0,
        end: 110,
        loc: [Object],
        program: [Object],
        comments: [],
        tokens: [Object] },
     code: '\nclass Component3a extends React.Component {\n  render() {\n    return React.createElement(\'div\', null);\n  }\n};\n',
     shebang: '',
     hub: Hub { file: [Circular], options: undefined },
     scope:
      Scope {
        uid: 0,
        parent: null,
        hub: [Object],
        parentBlock: [Object],
        block: [Object],
        path: [Object],
        labels: [Object],
        references: [Object],
        bindings: [Object],
        globals: [Object],
        uids: {},
        data: {},
        crawling: false } },
 //state.opts.knownComponents
  opts: {} }
